### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by PiJoules** [aras-p/ClangBuildAnalyzer#40]
I'm attempting to profile fuchsia compilations and am running into:

```
Analyzing build trace from '/tmp/capture-file'...
ERROR: corrupt input file '/tmp/capture-file' (checksum mismatch)
```

Do you have any ways of going about debugging this? This is from a fresh ClangBuildAnalyzer checkout and there didn't seem to be any issues with building or running it. I'm able to assert that `-ftime-trace` is working as intended since I can see the `.json` files in my build. The capture file I also made is about 470 MB.

**Comment by aras-p** [comment]
My wild guess is that it might be related to this fix #38 that I haven't merged yet -- there's a bug in writing out data file with _very long_ symbol names etc. I will try to actually test that case myself soon and merge the fix.

**Comment by aras-p** [comment]
Can you try with master branch now? If my guess was correct, then the merge of #38 should have fixed this. If it still does not work, then getting your json files somehow would be useful for fixing the issue.

**Comment by pseyfert** [comment]
Hi,
I see the same error message (building https://gitlab.cern.ch/lhcb/LHCb) with today's master of ClangBuildAnalyzer 858cc42908337b385a495bf70cc90363d71e60c9.

You can download my json files (for a few days) here if you want
https://cernbox.cern.ch/index.php/s/JVLy1bITaVOoZ7f

EDIT: I should add I tried the same json files on a different machine and here things work …

EDIT2: my bad, I exceeded the quota in my home directory which rightfully causes the corruption. After solving my filesystem issues I compared 5b2550eb6b84de6ea884511bc1eaed9bb75c6777 = v1.2.0 against 280e5c5d48d1a9d8807030845e4fc6ceb84b410a = master now. With the old version I get the checksum mismatch error. with the new version I don't get the error. So if @PiJoules's error is the same as the one I see with v1.2.0 then this should be fixed in the current master

**Comment by aras-p** [comment]
I'll assume this is fixed. Comment on the issue if it's still happening!
